{% set name = "Riskfolio-Lib" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6d897d4a197e381e1d8dffe8837d961827eda6af8ba8b167812ac0d591de946
  patches:
    - devendor-eigen-spectra.patch

build:
  number: 0
  noarch: python
  script:
    - find $PREFIX/include
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7
    - pip
    - numpy
    - pybind11 >=2.10.1
    - scipy >=1.1.0
    - setuptools >=68.1.0
    - wheel
    - eigen
    - spectra-cpp
  run:
    - python >=3.7
    - arch-py >=5.4
    - astropy >=5.1
    - clarabel >=0.6.0
    - cvxpy >=1.4.0
    - matplotlib-base >=3.7.0
    - networkx >=3.0
    - numpy >=1.24.0
    - pandas >=2.0.0
    - scikit-learn >=1.3.0
    - scipy >=1.10.0
    - statsmodels >=0.13.5
    - xlsxwriter >=3.1.2

test:
  imports:
    - riskfolio

outputs:
  - name: {{ name|lower }}
  - name: riskfolio_lib
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage( name|lower , exact=True) }}

about:
  home: https://github.com/dcajasn/Riskfolio-Lib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Portfolio Optimization and Quantitative Strategic Asset Allocation in Python
  dev_url: https://github.com/dcajasn/Riskfolio-Lib

extra:
  recipe-maintainers:
    - timkpaine
    - zklaus
